####################################################################
# Dune module information file: This file gets parsed by dunecontrol
# and by the CMake build scripts.
####################################################################
Module: opm-multidomain
Version: 2019.10-pre
Codename: Honey Bunny
Description: Implements coupling between multiple domains
Url: http://opm-project.org
MaintainerName: Runar Lie Berge
Maintainer: rube@norceresearch.no
Depends: opm-models
Suggests: opm-grid
